--------------------------------------------------------
--  DDL for Table COACH_TROPHIES
--------------------------------------------------------

  CREATE TABLE "FOOTBALL"."COACH_TROPHIES" 
   (	"COACH_ID" NUMBER, 
	"LEAGUE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SEASON" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PLACE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table COACHES
--------------------------------------------------------

  CREATE TABLE "FOOTBALL"."COACHES" 
   (	"COACH_ID" NUMBER, 
	"NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"FIRST_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"NATIONALITY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"BIRTH_DATE" DATE, 
	"BIRTH_PLACE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"BIRTH_COUNTRY" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"HEIGHT" NUMBER, 
	"WEIGHT" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table COACHES_CAREER
--------------------------------------------------------

  CREATE TABLE "FOOTBALL"."COACHES_CAREER" 
   (	"COACH_ID" NUMBER, 
	"TEAM_ID" NUMBER, 
	"START_DATE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"END_DATE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table COUNTRIES
--------------------------------------------------------

  CREATE TABLE "FOOTBALL"."COUNTRIES" 
   (	"COUNTRY" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"CODE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table LEAGUE
--------------------------------------------------------

  CREATE TABLE "FOOTBALL"."LEAGUE" 
   (	"LEAGUE_ID" NUMBER, 
	"NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRY_CODE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SEASON" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SEASON_START" DATE, 
	"SEASON_END" DATE, 
	"STANDINGS" NUMBER, 
	"IS_CURRENT" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table PLAYER
--------------------------------------------------------

  CREATE TABLE "FOOTBALL"."PLAYER" 
   (	"PLAYER_ID" NUMBER, 
	"PLAYER_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"FIRST_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"NATIONALITY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TEAM_ID" NUMBER, 
	"BIRTH_DATE" DATE, 
	"BIRTH_PLACE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"BIRTH_COUNTRY" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"HEIGHT" NUMBER, 
	"WEIGHT" NUMBER, 
	"RATING" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table PLAYER_STATS
--------------------------------------------------------

  CREATE TABLE "FOOTBALL"."PLAYER_STATS" 
   (	"PLAYER_ID" NUMBER, 
	"TEAM_ID" NUMBER, 
	"LEAGUE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SEASON" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"INJURED" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"RATING" NUMBER, 
	"CAPTAIN" NUMBER, 
	"GAME_APPEARENCES" NUMBER, 
	"GAMES_MINUTES_PLAYED" NUMBER, 
	"GAMES_LINEUPS" NUMBER, 
	"SUBSTITUTES_IN" NUMBER, 
	"SUBSTITUTES_OUT" NUMBER, 
	"SUBSTITUTES_BENCH" NUMBER, 
	"GOALS_TOTAL" NUMBER, 
	"ASSISTS" NUMBER, 
	"CONCEDED" NUMBER, 
	"SAVES" NUMBER, 
	"PASSES_TOTAL" NUMBER, 
	"KEY_PASS" NUMBER, 
	"PASS_ACCURACY" NUMBER, 
	"TACKLES_TOTAL" NUMBER, 
	"TACKLES_BLOCKS" NUMBER, 
	"TACKLES_INTERCEPTIONS" NUMBER, 
	"DUELS_TOTAL" NUMBER, 
	"DUELS_WON" NUMBER, 
	"DRIBBLES_ATTEMPTS" NUMBER, 
	"DRIBBLES_SUCCESS" NUMBER, 
	"FOULS_DRAWN" NUMBER, 
	"FOULS_COMMITED" NUMBER, 
	"SHOTS_TOTAL" NUMBER, 
	"SHOTS_ON" NUMBER, 
	"PENALTY_WON" NUMBER, 
	"PENALTY_COMMITED" NUMBER, 
	"PENALTY_SUCCESS" NUMBER, 
	"PENALTY_MISSED" NUMBER, 
	"PENALTY_SAVED" NUMBER, 
	"YELLOW_CARD" NUMBER, 
	"YELLOWRED" NUMBER, 
	"RED_CARD" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table PLAYER_TROPHIES
--------------------------------------------------------

  CREATE TABLE "FOOTBALL"."PLAYER_TROPHIES" 
   (	"PLAYER_ID" NUMBER, 
	"LEAGUE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SEASON" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PLACE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

--------------------------------------------------------
--  DDL for Table PLAYERTMARKT3
--------------------------------------------------------

  CREATE TABLE "FOOTBALL"."PLAYERTMARKT3" 
   (	"PLAYER_ID" NUMBER, 
	"PLAYER_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"FIRST_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_NAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TEAM" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"AGE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"NATIONALITY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH1" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH2" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH3" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"SEARCH4" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"MARKET_VALUE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table SEASONS
--------------------------------------------------------

  CREATE TABLE "FOOTBALL"."SEASONS" 
   (	"SEASON" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table STG_DATASET_PREMIER_LEAGUE
--------------------------------------------------------

  CREATE TABLE "FOOTBALL"."STG_DATASET_PREMIER_LEAGUE" 
   (	"LSISPL" NUMBER, 
	"LSSTATS" NUMBER, 
	"PLEX" NUMBER, 
	"SUMTEAMEXP" NUMBER, 
	"PL" NUMBER, 
	"TEAMEXP" NUMBER, 
	"LAST3SEASONTEAMCHANGE" NUMBER, 
	"GPMDIFFER" NUMBER, 
	"PLAYER_ID" NUMBER, 
	"LEAGUE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TEAM_ID" NUMBER, 
	"SEASON" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"L1" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"T1" NUMBER, 
	"S1" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"LAGTEAM" NUMBER, 
	"LAGTEAM2" NUMBER, 
	"LAGGMPLAY" NUMBER, 
	"CAPTAIN" NUMBER, 
	"GAME_APPEARENCES" NUMBER, 
	"GAMES_MINUTES_PLAYED" NUMBER, 
	"GAMES_LINEUPS" NUMBER, 
	"SUBSTITUTES_IN" NUMBER, 
	"SUBSTITUTES_OUT" NUMBER, 
	"SUBSTITUTES_BENCH" NUMBER, 
	"GOALS_TOTAL" NUMBER, 
	"ASSISTS" NUMBER, 
	"CONCEDED" NUMBER, 
	"SAVES" NUMBER, 
	"PASSES_TOTAL" NUMBER, 
	"KEY_PASS" NUMBER, 
	"PASS_ACCURACY" NUMBER, 
	"TACKLES_TOTAL" NUMBER, 
	"TACKLES_BLOCKS" NUMBER, 
	"TACKLES_INTERCEPTIONS" NUMBER, 
	"DUELS_TOTAL" NUMBER, 
	"DUELS_WON" NUMBER, 
	"DRIBBLES_ATTEMPTS" NUMBER, 
	"DRIBBLES_SUCCESS" NUMBER, 
	"FOULS_DRAWN" NUMBER, 
	"FOULS_COMMITED" NUMBER, 
	"SHOTS_TOTAL" NUMBER, 
	"SHOTS_ON" NUMBER, 
	"PENALTY_WON" NUMBER, 
	"PENALTY_COMMITED" NUMBER, 
	"PENALTY_SUCCESS" NUMBER, 
	"PENALTY_MISSED" NUMBER, 
	"PENALTY_SAVED" NUMBER, 
	"YELLOW_CARD" NUMBER, 
	"YELLOWRED" NUMBER, 
	"RED_CARD" NUMBER, 
	"POSITION" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"NATIONALITY" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"AGE" NUMBER, 
	"HEIGHT" NUMBER, 
	"WEIGHT" NUMBER, 
	"TARGET1" NUMBER, 
	"TARGET2" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TEAM
--------------------------------------------------------

  CREATE TABLE "FOOTBALL"."TEAM" 
   (	"TEAM_ID" NUMBER, 
	"NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"CODE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRY" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_NATIONAL" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"FOUNDED" NUMBER, 
	"VENUE_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"VENUE_SURFACE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"VENUE_ADDRESS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"VENUE_CITY" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"VENUE_CAPACITY" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TMP_1
--------------------------------------------------------

  CREATE TABLE "FOOTBALL"."TMP_1" 
   (	"PLAYER_ID" NUMBER, 
	"TEAM_ID" NUMBER, 
	"LEAGUE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SEASON" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"INJURED" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"RATING" NUMBER, 
	"CAPTAIN" NUMBER, 
	"GAME_APPEARENCES" NUMBER, 
	"GAMES_MINUTES_PLAYED" NUMBER, 
	"GAMES_LINEUPS" NUMBER, 
	"SUBSTITUTES_IN" NUMBER, 
	"SUBSTITUTES_OUT" NUMBER, 
	"SUBSTITUTES_BENCH" NUMBER, 
	"GOALS_TOTAL" NUMBER, 
	"ASSISTS" NUMBER, 
	"CONCEDED" NUMBER, 
	"SAVES" NUMBER, 
	"PASSES_TOTAL" NUMBER, 
	"KEY_PASS" NUMBER, 
	"PASS_ACCURACY" NUMBER, 
	"TACKLES_TOTAL" NUMBER, 
	"TACKLES_BLOCKS" NUMBER, 
	"TACKLES_INTERCEPTIONS" NUMBER, 
	"DUELS_TOTAL" NUMBER, 
	"DUELS_WON" NUMBER, 
	"DRIBBLES_ATTEMPTS" NUMBER, 
	"DRIBBLES_SUCCESS" NUMBER, 
	"FOULS_DRAWN" NUMBER, 
	"FOULS_COMMITED" NUMBER, 
	"SHOTS_TOTAL" NUMBER, 
	"SHOTS_ON" NUMBER, 
	"PENALTY_WON" NUMBER, 
	"PENALTY_COMMITED" NUMBER, 
	"PENALTY_SUCCESS" NUMBER, 
	"PENALTY_MISSED" NUMBER, 
	"PENALTY_SAVED" NUMBER, 
	"YELLOW_CARD" NUMBER, 
	"YELLOWRED" NUMBER, 
	"RED_CARD" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TMP_PREMIER_LEAGUE_TEAMS
--------------------------------------------------------

  CREATE TABLE "FOOTBALL"."TMP_PREMIER_LEAGUE_TEAMS" 
   (	"TEAM_ID" NUMBER, 
	"NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"CODE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNTRY" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_NATIONAL" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"FOUNDED" NUMBER, 
	"VENUE_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"VENUE_SURFACE" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"VENUE_ADDRESS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"VENUE_CITY" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"VENUE_CAPACITY" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table LEAGUE
--------------------------------------------------------

  ALTER TABLE "FOOTBALL"."LEAGUE" MODIFY ("LEAGUE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLAYER
--------------------------------------------------------

  ALTER TABLE "FOOTBALL"."PLAYER" MODIFY ("PLAYER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEAM
--------------------------------------------------------

  ALTER TABLE "FOOTBALL"."TEAM" MODIFY ("TEAM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TMP_PREMIER_LEAGUE_TEAMS
--------------------------------------------------------

  ALTER TABLE "FOOTBALL"."TMP_PREMIER_LEAGUE_TEAMS" MODIFY ("TEAM_ID" NOT NULL ENABLE);
